AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for product management app

Globals:
  Function:
    Timeout: 3

Resources:
  #Lambda function
  dbUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pdAppFunction
      CodeUri: dbUpdate/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        updateDb:
          Type: Api
          Properties:
            Path: /updatedb
            Method: post
      Environment:
        Variables:
          ddbTableName: !Ref database #Fetches database name
      Policies: AmazonDynamoDBFullAccess
  
  #DynamoDB Table
  database:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: productName
        Type: String
        TableName: pdAppDatabase